  #Act 1
label majordebriefing:
    scene bg starry sky
    show MGRneutral in center with None
    u "Major Revelation."
    u "Tell us about your latest progress."
    g "The Phoenix Heart has demonstrated its aptitude in simulation battles, proving to be -"
    u "That's just a machine."
    u "If we spent that much blood, sweat, and time, there had {i}better{/i} be more results than a mere minor improvement."
    u "In fact, this is hardly better than what you had all those years ago!"
    g "..."
    g "Ma'am."
    g "Respectfully, ma'am, we've had a shoestring budget since the accident fifteen years ago."
    g "It's impressive that we've recovered from that to this point, ma'am."
    u "But if all you've done is recreate the past, there was no point in wasting all that money and effort on your pet project."
    u "Don't get me wrong."
    u "You've been an otherwise exceptional researcher and soldier for us."
    u "You are professional, punctual, and brilliant."
    u "It's almost enough to clear your name, Traitor of Tchempo."
    g "Ma'am."
    u "Oh, spare me the backtalk. You know as well as I do that we did you a favor."
    u "If you had picked any other problem, I'm sure we'd be congratulating your successful research dissertation, and toasting your career."
    u "But you picked {i}this{/i}, and produced nothing."
    u "Are you {i}any{/i} closer to reproducing that anomalous incident?"
    g "Ma'am, as I've told you a thousand times before, we have very little understanding of the fundamental theory."
    g "It's only gotten worse since we've lost most of our budget and researchers to other projects, ma'am."
    u "And yet the show of force mission is in one month, with your own handpicked ace team as demonstrators."
    u "For your own good, and for the good of your team, I'd suggest you find a way to reproduce that light."
    g "Ma'am, I understand that. I know the show of force mission is in one month's time."
    g "In two weeks, we'll run the Phoenix Heart's all-up test."
    u "That's not good enough."
    u "'I believe' is not sufficient for the funding committee."
    u "I'm sorry."
    u "I know that that won't bring Hope back."
    u "But neither will throwing good money after bad."
    u "You know how this business is."
    u "It's publish or perish, unfortunately."
    u "A one-off miracle is only good as a tragic story, and worthless to the forward march of progress."
    u "It's not {i}useful{/i}."
    u "So this is a piece of advice."
    u "You seem to be laboring under the mistaken belief that you can keep everyone safe."
    u "But from Command's perspective, we're already choosing who lives, and who dies."
    u "It doesn't seem like your team can survive the show of force mission in one month as is."
    u "Decide whether you're comfortable sacrificing everyone because you didn't have the courage to reproduce {i}every{/i} aspect of the anomalous event fifteen years ago."
    u "You say that your all up test is in two weeks? That will be your deadline."
    u "Whether you can or can't achieve ignition is no longer relevant. The decision to move the show of force forward has already been decided."
    u "I suggest you move up the test one week."
    u "That will give you three weeks to write the letters to next of kin."
    u "Or, find a way to achieve ignition, and save everyone you can."
    u "That's the kind of toughness a commander needs."
    u "Am I clear?"
    g "..."
    g "Crystal."
    u "Wonderful."
    u "I look forward to your success."
    "< LINE DISCONNECTED >"
    g "..."
    g "'Anomalous event'."
    g "'Replicate it.'"
    g "That makes it sound so {b}bloodless{/b}."
    g "Hope gave up her life to save ours."
    g "..."
    g "What do I do now, H-"
    g "..."
    g "Forget it."
    g "I know what I need to do."
    g "I've always known."
    g "This has to have a reason."
    g "This research has to be justified."
    g "If it doesn't, then Hope sacrificed herself for {i}nothing{/i}!"
    g "I can't accept that."
    g "I can't give up."
    g "Not when the YURI core hasn't yet revealed all of its secrets."
    g "The damned core."
    g "It only responds to women."
    g "Only to our hearts."
    g "Only one at a time."
    g "But outside of a scant few ignition experiments, the paired tests never worked."
    g "What is it that I'm missing?"
    "< WITHOUT LOVE >"
    "< IT CANNOT BE SEEN >"
    g "..."
    g "Maybe it really is the devil I was warned about."
    g "Maybe it only works with sacrifice."
    g "If that's the case..."
    g "Hope really did die for nothing."
    g "But maybe that's the truth."
    g "...Recreating the past is pointless."
    g "But all the same, I can't rest unless I can settle this."
    g "It's science if you can repeat a miracle, huh."
    g "Is it still science, if you can make a miracle happen through monstrosity?"
    g "..."
    g "'Do whatever you need to?'"
    g "..."
    g "Fine. If I have to become a monster to complete this dream, so be it."
    g "One way or another, the work that Hope left us {i}will{/i} be finished."
    g "...because if it can't, we can't ever be forgiven."
    jump chase